// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juxywspkgpyscvwvqaon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eHl3c3BrZ3B5c2N2d3ZxYW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzM4ODEsImV4cCI6MjA2NTQ0OTg4MX0.z4yR01O6KSzADIwoX9V69tcX_Sk73pjOKJ_JtfvgMPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);